#ifndef INCLUDE_HAL_KEYPAD_KEYPAD_INTERFACE_H_
#define INCLUDE_HAL_KEYPAD_KEYPAD_INTERFACE_H_

// FUNCTIONS PROTOTYPES
void KEYPAD_voidInit(void);
u8 KEYPAD_u8GetPressedKey(void);


#endif /* INCLUDE_HAL_KEYPAD_KEYPAD_INTERFACE_H_ */
